/**
 * Browser-oriented entry: same implementation as `@beava/node` (global `fetch` only).
 * Depend on `@beava/client` in front-end apps; depend on `@beava/node` in Node services.
 */
export {
  BeavaError,
  BeavaResponseValidationError,
  createBeavaClient,
  batchGetEntrySchema,
  batchGetRequestSchema,
  batchGetResponseSchema,
  beavaErrorEnvelopeSchema,
  beavaWireErrorBodySchema,
  entityKeySchema,
  getRequestSchema,
  jsonObjectSchema,
  jsonValueSchema,
  pingResponseSchema,
  pushRequestSchema,
  pushResponseSchema,
  registerRequestSchema,
  registerResponseSchema,
  type BeavaClient,
  type BeavaClientOptions,
  type BeavaWireErrorBody,
  type BatchGetEntry,
  type BatchGetRequest,
  type EntityKey,
  type GetRequest,
  type JsonObject,
  type JsonValue,
  type PingResponse,
  type PushRequest,
  type PushResponse,
  type RegisterRequest,
  type RegisterResponse,
} from "@beava/node";
